name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
      uses: actions/checkout@v2

      - name: Install dependencies
      run